---
- hosts: all
  tasks:
    - name: create a empty file
      file:
        dest: /tmp/file
        state: '{{ file_state }}'
- hosts: web
  tasks:
    - name: create a empty file
      file:
        dest: /tmp/web-file
        state: '{{ file_state }}'
- hosts: all:!db
  tasks:
    - name: create a empty file
      file:
        dest: /tmp/web-not-db-file
        state: '{{ file_state }}'
- hosts: all:&backup:!web
  tasks:
    - name: create an empty file on backup 
      file:
        dest: /tmp/all-but-not-web&backup
        state: '{{ file_state1 }}'
- hosts: backup
  tasks:
    - name: create an empty file on backup 
      file:
        dest: /tmp/only-on-backup
        state: '{{ file_state2 }}'
- hosts: all:!web:!backup
  tasks:
    - name: create empty file on slave3
      file:
        dest: /tmp/only-on-slave3
        state: '{{ file_state3 }}'
# | doesnot work & selects the particular
- hosts: all:|web:|db
  tasks:
    - name: create empty file on either
      file:
        dest: /tmp/either-file
        state: '{{ file_state4 }}'
